export const theme = Object.freeze({
  colors: {
    white: '#ffffff',
    dark_grey: '#3E3D4A',
    dark: '#000000',
    black_btn: '#303030',
    red: '#CE1700',
    blue: '#D9DBE9',
    text: '#3E3D4A',
    secondaryText: '#757575',
    body_bg: '#FAFAFA',
    tomato: 'tomato',
    grey_1: '#EFEFF0',
    link: '#007aff',
    input_bg: '#f1f1f5',
    placeholder: '#6E7191',
    privacy_bg: '#E3E3EB',
    primary: '#7058FF',
    body_svg: '#f9f9f9',
    orange: '#FFAA00',
    grey_off: '#C9CAD4',
    grey_purple: '#A0A3BD',
  },
  size: {
    mobile: '375px',
    tablet: '768px',
    default: '960px',
    desktop: '1440px',
  },
  device: {
    mobile: `@media screen and (min-width:340px)`,
    mobileMax: `@media screen and (max-width:767px)`,
    tablet: `@media screen and (min-width: 768px)`,
    tabletOnly: `@media screen and (min-width: 768px) and (max-width: 959px)`,
    default: `@media screen and (min-width: 960px)`,
    defaultonly: `@media only screen and (min-width: 960px) and (max-width: 1439px)`,
    desktop: `@media screen and (min-width: 1440px)`,
  },
  fonts: {
    title: {
      semiBold: 'Montserrat_SemiBold',
      bold: 'Montserrat_Bold',
    },
    descr: {
      regular: 'Poppins_Regular',
      semiBold: 'Poppins_SemiBold',
      bold: 'Poppins_Bold',
    },
  },
  spacing: value => `${4 * value}px`,
});
